-- Disable RLS on all tables so the anon key can read/write
-- Run this in Supabase SQL Editor: https://supabase.com/dashboard/project/jizagahrnywfohhwcpoh/sql/new

ALTER TABLE temples DISABLE ROW LEVEL SECURITY;
ALTER TABLE products DISABLE ROW LEVEL SECURITY;
ALTER TABLE packages DISABLE ROW LEVEL SECURITY;
ALTER TABLE package_products DISABLE ROW LEVEL SECURITY;
ALTER TABLE runners DISABLE ROW LEVEL SECURITY;
ALTER TABLE runner_temples DISABLE ROW LEVEL SECURITY;
ALTER TABLE customers DISABLE ROW LEVEL SECURITY;
ALTER TABLE orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE runner_receipts DISABLE ROW LEVEL SECURITY;
ALTER TABLE runner_payments DISABLE ROW LEVEL SECURITY;
ALTER TABLE disputes DISABLE ROW LEVEL SECURITY;
ALTER TABLE temple_requests DISABLE ROW LEVEL SECURITY;
ALTER TABLE notifications DISABLE ROW LEVEL SECURITY;
ALTER TABLE settings DISABLE ROW LEVEL SECURITY;
